language: php
php:
- 7.2
sudo: required
before_install:
  - openssl aes-256-cbc -K $encrypted_19ac19315506_key -iv $encrypted_19ac19315506_iv
    -in secrets.tar.enc -out secrets.tar -d
  - tar xvf secrets.tar
script:
- phpunit res/code
- mv key_file res/code/key_file
- mv secret.yaml res/code/secret.yaml
before_deploy:
  - cd res/code
deploy:
  skip_cleanup: true
  provider: gae
  keyfile: key_file
  project: learned-surge-247409

