language: php
php:
- 7.1
sudo: required
before_install:
  - openssl aes-256-cbc -K $encrypted_19ac19315506_key -iv $encrypted_19ac19315506_iv
    -in secrets.tar.enc -out secrets.tar -d
  - tar xvf secrets.tar
script:
- phpunit
- mv key_file res/code/key_file
- mv secret.yaml res/code/secret.yaml
- build.sh
deploy:
  provider: gae
  keyfile: key_file
  project: learned-surge-247409
dd:

